"""add column deleted_at

Revision ID: 2caa1e694422
Revises: 0d6bb4cb7d48
Create Date: 2023-11-28 14:28:47.009947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2caa1e694422'
down_revision = '0d6bb4cb7d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
