"""update column is_attending in table booking_user

Revision ID: 6aaf27abe78f
Revises: b7c22e6d3e65
Create Date: 2023-12-18 15:34:10.518708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6aaf27abe78f'
down_revision = 'b7c22e6d3e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_user', schema=None) as batch_op:
        batch_op.alter_column('is_attending',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_user', schema=None) as batch_op:
        batch_op.alter_column('is_attending',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###
